--
-- Script was generated by Devart dbForge Studio 2019 for SQL Server, Version 5.7.31.0
-- Product home page: http://www.devart.com/dbforge/sql/studio
-- Script date 09.08.2019 15:35:41
-- Server version: 14.00.2027
--



USE Blog
GO

IF DB_NAME() <> N'Blog' SET NOEXEC ON
GO

--
-- Create table [dbo].[Subscriber]
--
PRINT (N'Create table [dbo].[Subscriber]')
GO
CREATE TABLE dbo.Subscriber (
  id int IDENTITY,
  UserName nvarchar(max) NULL,
  Email nvarchar(max) NULL,
  Date datetime NULL,
  CONSTRAINT PK_Subscriber_id PRIMARY KEY CLUSTERED (id)
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO

--
-- Create table [dbo].[FeedBack]
--
PRINT (N'Create table [dbo].[FeedBack]')
GO
CREATE TABLE dbo.FeedBack (
  id int IDENTITY,
  FeedBackMessage nvarchar(max) NULL,
  Name nvarchar(max) NULL,
  Contact nvarchar(max) NULL,
  CONSTRAINT PK_FeedBack_id PRIMARY KEY CLUSTERED (id)
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO

--
-- Create table [dbo].[Category]
--
PRINT (N'Create table [dbo].[Category]')
GO
CREATE TABLE dbo.Category (
  Id int IDENTITY,
  Name nvarchar(max) NULL,
  CONSTRAINT PK_Category_Id PRIMARY KEY CLUSTERED (Id)
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO

--
-- Create table [dbo].[SubCategory]
--
PRINT (N'Create table [dbo].[SubCategory]')
GO
CREATE TABLE dbo.SubCategory (
  Id int IDENTITY,
  Name nvarchar(max) NULL,
  CategoryID int NOT NULL,
  CONSTRAINT PK_SubCategory_Id PRIMARY KEY CLUSTERED (Id)
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO

--
-- Create foreign key [FK_SubCategory_Category_Id] on table [dbo].[SubCategory]
--
PRINT (N'Create foreign key [FK_SubCategory_Category_Id] on table [dbo].[SubCategory]')
GO
ALTER TABLE dbo.SubCategory
  ADD CONSTRAINT FK_SubCategory_Category_Id FOREIGN KEY (CategoryID) REFERENCES dbo.Category (Id) ON DELETE CASCADE ON UPDATE CASCADE
GO

--
-- Create table [dbo].[Article]
--
PRINT (N'Create table [dbo].[Article]')
GO
CREATE TABLE dbo.Article (
  Id int IDENTITY,
  Name nvarchar(max) NULL,
  Description nvarchar(max) NULL,
  SubCategoryID int NOT NULL,
  ImageLink nvarchar(max) NULL,
  Date datetime NULL,
  Raiting int NULL,
  CONSTRAINT PK_Book_Id PRIMARY KEY CLUSTERED (Id)
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO

--
-- Create foreign key [FK_Book] on table [dbo].[Article]
--
PRINT (N'Create foreign key [FK_Book] on table [dbo].[Article]')
GO
ALTER TABLE dbo.Article
  ADD CONSTRAINT FK_Book FOREIGN KEY (SubCategoryID) REFERENCES dbo.SubCategory (Id) ON DELETE CASCADE ON UPDATE CASCADE
GO

--
-- Create table [dbo].[Author]
--
PRINT (N'Create table [dbo].[Author]')
GO
CREATE TABLE dbo.Author (
  Id int IDENTITY,
  FirstName nvarchar(max) NULL,
  LastName nvarchar(max) NULL,
  MiddleName nvarchar(max) NULL,
  ArticleID int NOT NULL,
  CONSTRAINT PK_Author_Id PRIMARY KEY CLUSTERED (Id)
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO

--
-- Create foreign key [FK_Author_Article_Id] on table [dbo].[Author]
--
PRINT (N'Create foreign key [FK_Author_Article_Id] on table [dbo].[Author]')
GO
ALTER TABLE dbo.Author
  ADD CONSTRAINT FK_Author_Article_Id FOREIGN KEY (ArticleID) REFERENCES dbo.Article (Id) ON DELETE CASCADE ON UPDATE CASCADE
GO

--
-- Create table [dbo].[ArticleDetail]
--
PRINT (N'Create table [dbo].[ArticleDetail]')
GO
CREATE TABLE dbo.ArticleDetail (
  id int IDENTITY,
  Text nvarchar(max) NULL,
  ArticleID int NOT NULL,
  Image nvarchar(max) NULL,
  [Like] int NULL,
  Unlike int NULL,
  Description nvarchar(max) NULL,
  Date datetime NULL,
  Name nvarchar(max) NULL,
  CONSTRAINT PK_Article_id PRIMARY KEY CLUSTERED (id),
  CONSTRAINT KEY_Article_bookID UNIQUE (ArticleID)
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO

--
-- Create foreign key [FK_Article_Book_Id] on table [dbo].[ArticleDetail]
--
PRINT (N'Create foreign key [FK_Article_Book_Id] on table [dbo].[ArticleDetail]')
GO
ALTER TABLE dbo.ArticleDetail
  ADD CONSTRAINT FK_Article_Book_Id FOREIGN KEY (ArticleID) REFERENCES dbo.Article (Id) ON DELETE CASCADE ON UPDATE CASCADE
GO

--
-- Create table [dbo].[Video]
--
PRINT (N'Create table [dbo].[Video]')
GO
CREATE TABLE dbo.Video (
  id int IDENTITY,
  Title nvarchar(max) NULL,
  Description nvarchar(max) NULL,
  Duration nvarchar(max) NULL,
  Url nvarchar(max) NULL,
  Image nvarchar(max) NULL,
  ArticleDetailID int NOT NULL,
  CONSTRAINT PK_Video_id PRIMARY KEY CLUSTERED (id)
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO

--
-- Create foreign key [FK_Video_ArticleDetail_id] on table [dbo].[Video]
--
PRINT (N'Create foreign key [FK_Video_ArticleDetail_id] on table [dbo].[Video]')
GO
ALTER TABLE dbo.Video
  ADD CONSTRAINT FK_Video_ArticleDetail_id FOREIGN KEY (ArticleDetailID) REFERENCES dbo.ArticleDetail (id) ON DELETE CASCADE ON UPDATE CASCADE
GO

--
-- Create table [dbo].[OuterDownladLink]
--
PRINT (N'Create table [dbo].[OuterDownladLink]')
GO
CREATE TABLE dbo.OuterDownladLink (
  id int IDENTITY,
  Title nvarchar(max) NULL,
  FileShareLink nvarchar(max) NULL,
  ArticleDetailID int NOT NULL,
  CONSTRAINT PK_OuterDownladLink_id PRIMARY KEY CLUSTERED (id)
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO

--
-- Create foreign key [FK_OuterDownladLink_ArticleDetail_id] on table [dbo].[OuterDownladLink]
--
PRINT (N'Create foreign key [FK_OuterDownladLink_ArticleDetail_id] on table [dbo].[OuterDownladLink]')
GO
ALTER TABLE dbo.OuterDownladLink
  ADD CONSTRAINT FK_OuterDownladLink_ArticleDetail_id FOREIGN KEY (ArticleDetailID) REFERENCES dbo.ArticleDetail (id) ON DELETE CASCADE ON UPDATE CASCADE
GO

--
-- Create table [dbo].[Download]
--
PRINT (N'Create table [dbo].[Download]')
GO
CREATE TABLE dbo.Download (
  id int IDENTITY,
  Title nvarchar(max) NULL,
  Url nvarchar(max) NULL,
  ArticleDetailID int NOT NULL,
  CONSTRAINT PK_Download_id PRIMARY KEY CLUSTERED (id)
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO

--
-- Create foreign key [FK_Download_ArticleDetail_id] on table [dbo].[Download]
--
PRINT (N'Create foreign key [FK_Download_ArticleDetail_id] on table [dbo].[Download]')
GO
ALTER TABLE dbo.Download
  ADD CONSTRAINT FK_Download_ArticleDetail_id FOREIGN KEY (ArticleDetailID) REFERENCES dbo.ArticleDetail (id) ON DELETE CASCADE ON UPDATE CASCADE
GO

--
-- Create table [dbo].[Comment]
--
PRINT (N'Create table [dbo].[Comment]')
GO
CREATE TABLE dbo.Comment (
  id int IDENTITY,
  Message nvarchar(max) NULL,
  Date datetime NULL,
  ArticleDeatilID int NOT NULL,
  UserName nvarchar(max) NULL,
  UserID nvarchar(max) NOT NULL,
  UserEmail nvarchar(max) NULL,
  [Like] int NULL,
  Unlike int NULL,
  LinkToFile nvarchar(max) NULL,
  CONSTRAINT PK_Comment_id PRIMARY KEY CLUSTERED (id)
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO

--
-- Create foreign key [FK_Comment_ArticleDetail_id] on table [dbo].[Comment]
--
PRINT (N'Create foreign key [FK_Comment_ArticleDetail_id] on table [dbo].[Comment]')
GO
ALTER TABLE dbo.Comment
  ADD CONSTRAINT FK_Comment_ArticleDetail_id FOREIGN KEY (ArticleDeatilID) REFERENCES dbo.ArticleDetail (id) ON DELETE CASCADE ON UPDATE CASCADE
GO

--
-- Create table [dbo].[About]
--
PRINT (N'Create table [dbo].[About]')
GO
CREATE TABLE dbo.About (
  id int IDENTITY,
  AboutMe nvarchar(max) NULL,
  CONSTRAINT PK_About_id PRIMARY KEY CLUSTERED (id)
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO
SET NOEXEC OFF
GO